# Generated by Django 3.0.2 on 2020-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200407_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
