# Generated by Django 3.0.2 on 2020-04-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200406_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.post'),
        ),
    ]
