# Generated by Django 3.0.2 on 2020-04-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200411_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.BooleanField(default=False)),
                ('plikes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heart', to='blog_app.post')),
            ],
        ),
    ]
