# Generated by Django 3.0.2 on 2020-04-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comm',
            field=models.BooleanField(default=False),
        ),
    ]
