# Generated by Django 3.0.2 on 2020-04-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20200406_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comm',
            field=models.BooleanField(default=True),
        ),
    ]
