# Generated by Django 3.0.2 on 2020-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20200417_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
