# Generated by Django 3.0.2 on 2020-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20200418_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
