# Generated by Django 3.1 on 2020-09-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20200502_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog_app.userinfo'),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='plikes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heart', to='blog_app.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.ManyToManyField(to='blog_app.userinfo'),
        ),
    ]
